### ISSUE TITLE
How do you calculate 3d path(co-ordinates) b/w keyframes ?

### ISSUE THREAD

**Issue by crazyhitty** [CircuitLord/creatorscamera#1]
Just checked the tool and was curious how this feature was implemented.

**Comment by CircuitLord** [comment]
Well, it's not actually a 3d path, it's just a bunch of math trickery.

I calculate the average value of the controller sticks between each keyframe, and then move that speed in the playback. When transitioning to a new keyframe, I lerp in between the current move speed and the new average speed for the next keyframe, to make it turn smoothly.

Hopefully that helped. :) If you have any other questions, you can join me on my Discord here: https://discord.gg/gXDdhEj
I'd be happy to chat about it. :)

**Comment by crazyhitty** [comment]
Ah, do you record all the controller stick values between keyframes?

**Comment by crazyhitty** [comment]
Sorry, just checked the source code, I thought this project wasn't open sourced (didn't check readme properly :S). I checked this [file](https://gitlab.com/CircuitLord/creators-camera/blob/master/WpfApp1/Windows/CCNewUI.xaml.cs) and got a basic gist of how you record paths. Also, any particular reason to move away from Github?

**Comment by CircuitLord** [comment]
I actually open sourced it properly right after you had commented here, so that's probably why you didn't notice :)

Glad my code was at least somewhat readable to you :D

I'm just moving away from github since they kind of limit features unless you pay (like not being able to have private repos) and because they got bought by Microsoft (which I don't mind that much, but I like GitLabs more).

**Comment by crazyhitty** [comment]
Good work though, really appreciate for open sourcing it :)
